### ISSUE TITLE
TypeScript usage

### ISSUE THREAD

**Issue by k1r0s** [GoogleChromeLabs/clooney#29]
facing an error with TS
```
ERROR in [at-loader] ./node_modules/clooneyjs/clooney.d.ts:14:25 
    TS2307: Cannot find module 'comlink'.
```

here
https://github.com/GoogleChromeLabs/clooney/blob/master/dist/clooney.d.ts#L14
I see here that you're exporting this: 

`export { Comlink } from 'comlink';`

but module doens't have that name.. 

Should be 
`export { Comlink } from 'comlinkjs';`
right?

**Comment by surma** [comment]
I wasn‘t aware that TS expect npm module names. I’ll look into this

**Comment by surma** [comment]
This should hopefully be fixed in 0.6.3 via f97e1b9300a315986885f00c80c256e88927461c. Can you check?

**Comment by k1r0s** [comment]
i let you know if something goes wrong, thanks!

**Comment by k1r0s** [comment]
I just updated to the latest release and issue is still hapening

npm ls | grep cloo
├── clooneyjs@0.6.3

```
ERROR in [at-loader] ./node_modules/clooneyjs/clooney.d.ts:13:26 
    TS2307: Cannot find module 'comlinkjs'.

```

**Comment by surma** [comment]
Can you show me the project setup or something so I can test locally and figure this out?

**Comment by k1r0s** [comment]
Setup a project with this

    "webpack": "~3.8.1",
    "webpack-dev-server": "~2.9.3"
    "awesome-typescript-loader": "~3.2.3",
    "typescript": "~2.5.3"
    "clooneyjs": "^0.6.3",

Write a ts file: 

```typescript

import * as Clooney from "cloneyjs"

Clooney.spawn(whatEver, [...args])

```

Try to compile it

It will fail when loading typings, thats it

**Comment by k1r0s** [comment]
You should either remove the module from .d.ts file or declare it, but empty. I don't know why you are declaring the module over typescript if this is never exposed to the implementation :s

**Comment by surma** [comment]
It is exposed via `Clooney.Comlink`, in case someone wants to tweak Comlink’s transferhandlers.

Thanks for the test case. My hunch is that I just need to publish my `tsconfig.json` to npm. I’ll get back to you!

**Comment by k1r0s** [comment]
Appreciated @surma :)

**Comment by surma** [comment]
Okay, I published 0.6.4 that has Comlink as a `dependency` instead of a `devDependency`, so that `comlink.d.ts` is available. It now works for me locally (similar setup to your test case). Please confirm.

**Comment by k1r0s** [comment]
Confirmed, thanks @surma

**Comment by surma** [comment]
🎉 Thanks for your patience @k1r0s!
